#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
PKG="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$PKG/scripts/doctor.sh" "$ROOT"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP="$ROOT/backups/sbp-058-$STAMP"
mkdir -p "$BACKUP/seymour-bitcoin-node" "$BACKUP/seymour-bch-node" "$BACKUP/seymour-blockchain-manager/data/web"
cp -a "$ROOT/seymour-bitcoin-node/docker-compose.yml" "$BACKUP/seymour-bitcoin-node/docker-compose.yml"
cp -a "$ROOT/seymour-bch-node/docker-compose.yml" "$BACKUP/seymour-bch-node/docker-compose.yml"
cp -a "$ROOT/seymour-blockchain-manager/data/web/installer.py" "$BACKUP/seymour-blockchain-manager/data/web/installer.py"
python3 "$PKG/scripts/patch.py" "$ROOT"
cp "$PKG/payload/tests/test_runtime_storage_binding_execution.py" "$ROOT/tests/test_runtime_storage_binding_execution.py"
printf '%s\n' "$BACKUP" > "$ROOT/backups/sbp-058-latest"
echo "Backup: $BACKUP"
echo "SBP-058 BTC runtime storage binding installed: PASS"
echo "SBP-058 BCH runtime storage binding installed: PASS"
echo "SBP-058 installer binding execution contract installed: PASS"
echo "SBP-058 install: PASS"
echo "No blockchain runtime was restarted and no blockchain data was moved."
