#!/usr/bin/env bash
set -euo pipefail
PKG="$(cd "$(dirname "$0")/.." && pwd)"
REPO="$(cd "$PKG/../.." && pwd)"
LIVE="/home/umbrel/umbrel/app-data/seymour-blockchain-manager/data"
"$PKG/scripts/doctor.sh"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP="$REPO/backups/sbp-063.3.7-$STAMP"
mkdir -p "$BACKUP/repository/web" "$BACKUP/repository/shared/umbrel_control" "$BACKUP/live/web" "$BACKUP/live/shared/umbrel_control"
for f in web/app.js web/installer.py shared/umbrel_control/bridge.py shared/umbrel_control/http_client.py; do
  src="$REPO/seymour-blockchain-manager/data/$f"
  [ -f "$src" ] && cp -a "$src" "$BACKUP/repository/$f"
  live="$LIVE/$f"
  [ -f "$live" ] && cp -a "$live" "$BACKUP/live/$f"
done
mkdir -p "$REPO/seymour-blockchain-manager/data/shared/umbrel_control" "$LIVE/shared/umbrel_control"
cp -a "$PKG/payload/web/app.js" "$REPO/seymour-blockchain-manager/data/web/app.js"
cp -a "$PKG/payload/web/installer.py" "$REPO/seymour-blockchain-manager/data/web/installer.py"
cp -a "$PKG/payload/shared/umbrel_control/bridge.py" "$REPO/seymour-blockchain-manager/data/shared/umbrel_control/bridge.py"
cp -a "$PKG/payload/shared/umbrel_control/http_client.py" "$REPO/seymour-blockchain-manager/data/shared/umbrel_control/http_client.py"
echo "SBP-063.3.7 repository source synchronized: PASS"
cp -a "$PKG/payload/web/app.js" "$LIVE/web/app.js"
cp -a "$PKG/payload/web/installer.py" "$LIVE/web/installer.py"
cp -a "$PKG/payload/shared/umbrel_control/bridge.py" "$LIVE/shared/umbrel_control/bridge.py"
cp -a "$PKG/payload/shared/umbrel_control/http_client.py" "$LIVE/shared/umbrel_control/http_client.py"
echo "SBP-063.3.7 installed Blockchain Manager source synchronized: PASS"
echo "Backup: $BACKUP"
echo "SBP-063.3.7 install: PASS"
echo "No blockchain runtime was installed, stopped, restarted, recreated, or uninstalled."
echo "NEXT: run verify.sh, then restart Blockchain Manager only."
