#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
PKG="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$PKG/scripts/doctor.sh" "$ROOT"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP="$ROOT/backups/sbp-054-$STAMP"
mkdir -p "$BACKUP"
[[ ! -d "$ROOT/shared/blockchain_install" ]] || cp -a "$ROOT/shared/blockchain_install" "$BACKUP/"
[[ ! -f "$ROOT/shared/contracts/blockchain-install-preflight-v1.json" ]] || cp -a "$ROOT/shared/contracts/blockchain-install-preflight-v1.json" "$BACKUP/"
[[ ! -f "$ROOT/tests/test_blockchain_install_preflight.py" ]] || cp -a "$ROOT/tests/test_blockchain_install_preflight.py" "$BACKUP/"
mkdir -p "$ROOT/shared/blockchain_install" "$ROOT/shared/contracts" "$ROOT/tests"
cp -a "$PKG/payload/shared/blockchain_install/." "$ROOT/shared/blockchain_install/"
cp "$PKG/payload/shared/contracts/blockchain-install-preflight-v1.json" "$ROOT/shared/contracts/"
cp "$PKG/payload/tests/test_blockchain_install_preflight.py" "$ROOT/tests/"
printf '%s\n' "$BACKUP" > "$ROOT/backups/sbp-054-latest"
echo "Backup: $BACKUP"
echo "SBP-054 shared blockchain install foundation installed: PASS"
echo "SBP-054 storage target model installed: PASS"
echo "SBP-054 preflight contract installed: PASS"
echo "SBP-054 install: PASS"
echo "No blockchain runtime was started, stopped, restarted, or moved."
echo "No remote storage was configured."
