#!/usr/bin/env bash
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PKG="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP="$REPO/backups/sbp-064-$STAMP"
"$PKG/scripts/doctor.sh"
mkdir -p "$BACKUP/seymour-blockchain-manager/data/web"
cp -a "$REPO/seymour-blockchain-manager/data/web/telemetry.py" "$BACKUP/seymour-blockchain-manager/data/web/telemetry.py"
cp -a "$REPO/seymour-blockchain-manager/data/web/app.js" "$BACKUP/seymour-blockchain-manager/data/web/app.js"
cp -a "$PKG/payload/seymour-blockchain-manager/data/web/runtime_health.py" "$REPO/seymour-blockchain-manager/data/web/runtime_health.py"
"$PKG/scripts/patch.py" "$REPO"
LIVE="/home/umbrel/umbrel/app-data/seymour-blockchain-manager/data"
cp -a "$REPO/seymour-blockchain-manager/data/web/runtime_health.py" "$LIVE/web/runtime_health.py"
cp -a "$REPO/seymour-blockchain-manager/data/web/telemetry.py" "$LIVE/web/telemetry.py"
cp -a "$REPO/seymour-blockchain-manager/data/web/app.js" "$LIVE/web/app.js"
echo "$BACKUP" > "$REPO/backups/sbp-064-last-backup"
echo "SBP-064 repository source synchronized: PASS"
echo "SBP-064 installed Blockchain Manager source synchronized: PASS"
echo "Backup: $BACKUP"
echo "SBP-064 install: PASS"
echo "No blockchain runtime was installed, stopped, started, restarted, recreated, or uninstalled."
echo "NEXT: run verify.sh, then restart Blockchain Manager only."
