#!/usr/bin/env bash
set -euo pipefail
REPO="${1:-/home/umbrel/seymour-umbrel-app-store-git}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP="$REPO/backups/sbp-013-$STAMP"
"$ROOT/scripts/doctor.sh" "$REPO"
mkdir -p "$BACKUP"
cp -a "$REPO/seymour-blockchain-manager" "$BACKUP/"
cp "$ROOT/payload/seymour-blockchain-manager/data/web/adoption.py" "$REPO/seymour-blockchain-manager/data/web/adoption.py"
cd "$REPO"
python3 "$ROOT/payload/patch_app.py"
python3 "$ROOT/payload/patch_compose.py"
mkdir -p "$REPO/tests"
cp "$ROOT/payload/tests/test_adoption.py" "$REPO/tests/"
cp "$ROOT/payload/tests/test_adoption_ui.py" "$REPO/tests/"
echo "Backup: $BACKUP"
echo "SBP-013 install: PASS"
echo "No live BCH datadir was copied or modified."
echo "No live Umbrel app was restarted."
