#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
PKG="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$PKG/scripts/doctor.sh" "$ROOT"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP="$ROOT/backups/sbp-060.9-$STAMP"
mkdir -p "$BACKUP" "$ROOT/tests"
cp -a "$ROOT/shared/blockchain_recovery/models.py" "$BACKUP/models.py"
cp -a "$ROOT/shared/blockchain_recovery/engine.py" "$BACKUP/engine.py"
cp -a "$ROOT/scripts/seymour-blockchain-heal" "$BACKUP/seymour-blockchain-heal"
cp -a "$ROOT/seymour-bitcoin-node/docker-compose.yml" "$BACKUP/bitcoin-docker-compose.yml"
cp "$PKG/payload/shared/blockchain_recovery/port_guard.py" "$ROOT/shared/blockchain_recovery/port_guard.py"
cp "$PKG/payload/tests/test_port_conflict.py" "$ROOT/tests/test_port_conflict.py"
python3 "$PKG/scripts/patch.py"
chmod +x "$ROOT/scripts/seymour-blockchain-heal"
echo "Backup: $BACKUP"
echo "SBP-060.9 runtime port conflict detection installed: PASS"
echo "SBP-060.9 safe candidate selection installed: PASS"
echo "SBP-060.9 BTC configurable host P2P port installed: PASS"
echo "SBP-060.9 install: PASS"
echo "No runtime was restarted and no existing port owner was stopped."
