#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
PKG="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$PKG/scripts/doctor.sh" "$ROOT"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP="$ROOT/backups/sbp-060.4-$STAMP"
mkdir -p "$BACKUP" "$ROOT/shared/blockchain_recovery" "$ROOT/shared/contracts" "$ROOT/tests"
cp -a "$PKG/payload/shared/blockchain_recovery/." "$ROOT/shared/blockchain_recovery/"
cp "$PKG/payload/shared/contracts/blockchain-runtime-recovery-v1.json" "$ROOT/shared/contracts/"
cp "$PKG/payload/scripts/seymour-blockchain-heal" "$ROOT/scripts/"
cp "$PKG/payload/tests/test_blockchain_runtime_recovery.py" "$ROOT/tests/"
chmod +x "$ROOT/scripts/seymour-blockchain-heal"
printf '%s\n' "$BACKUP" > "$ROOT/backups/sbp-060.4-latest"
echo "Backup: $BACKUP"
echo "SBP-060.4 recovery engine installed: PASS"
echo "SBP-060.4 bounded safe-repair CLI installed: PASS"
echo "SBP-060.4 recovery evidence contract installed: PASS"
echo "SBP-060.4 install: PASS"
echo "No runtime was restarted and no blockchain data was modified."
