#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
PKG="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$PKG/scripts/doctor.sh" "$ROOT"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP="$ROOT/backups/sbp-059-$STAMP"
mkdir -p "$BACKUP/seymour-blockchain-manager/data/web"
cp -a "$ROOT/seymour-blockchain-manager/data/web/installer.py" "$BACKUP/seymour-blockchain-manager/data/web/installer.py"
cp -a "$ROOT/seymour-blockchain-manager/data/web/app.js" "$BACKUP/seymour-blockchain-manager/data/web/app.js"
python3 "$PKG/scripts/patch.py" "$ROOT"
cp "$PKG/payload/tests/test_provider_neutral_installer.py" "$ROOT/tests/test_provider_neutral_installer.py"
printf '%s\n' "$BACKUP" > "$ROOT/backups/sbp-059-latest"
echo "Backup: $BACKUP"
echo "SBP-059 BTC provider execution installed: PASS"
echo "SBP-059 BCH provider execution installed: PASS"
echo "SBP-059 provider-driven install UI installed: PASS"
echo "SBP-059 install: PASS"
echo "No blockchain installation was executed."
