from pathlib import Path
import sys
root=Path(sys.argv[1]); web=root/'seymour-blockchain-manager/data/web'; app=web/'app.py'; js=web/'app.js'; css=web/'style.css'
s=app.read_text()
if 'from sync_performance import analyze as analyze_sync_performance' not in s:
    s=s.replace('from sync_manager import analyze\n','from sync_manager import analyze\nfrom sync_performance import analyze as analyze_sync_performance\n',1)
if 'if self.path == "/api/sync/performance":' not in s:
    anchor='''        if self.path == "/api/sync":\n            self.send_json(analyze(dashboard_payload()))\n            return\n'''
    repl='''        if self.path == "/api/sync/performance":\n            self.send_json(analyze_sync_performance())\n            return\n\n        if self.path == "/api/sync":\n            self.send_json(analyze(dashboard_payload()))\n            return\n'''
    if anchor not in s: raise SystemExit('SBP-047 patch: /api/sync route anchor missing')
    s=s.replace(anchor,repl,1)
app.write_text(s)
s=js.read_text(); start=s.find('async function showSyncManager(providerId) {'); end=s.find('\nasync function fetchJsonWithTimeout(',start)
if start<0 or end<0: raise SystemExit('SBP-047 patch: showSyncManager boundaries missing')
replacement=r'''async function showSyncManager(providerId) {
  const provider = state.providers.find((item) => item.providerId === providerId);
  const response = await fetch("/api/sync", {cache: "no-store"});
  const sync = await response.json();
  const recommendations = sync.recommendations.map((item) => `<li class="recommendation ${item.severity}"><strong>${item.code}</strong><span>${item.message}</span></li>`).join("");
  dialogContent.innerHTML = `
    <p class="provider-family">initial sync manager</p><h2>${provider.displayName}</h2>
    <div class="sync-manager-tabs"><button class="sync-tab active" data-sync-view="status">Status</button><button class="sync-tab" data-sync-view="performance">Performance</button></div>
    <section id="syncStatusView"><div class="sync-kpis"><article><span>Progress</span><strong>${sync.snapshot.progress_percent ?? "—"}%</strong></article><article><span>Blocks remaining</span><strong>${sync.blocksRemaining ?? "—"}</strong></article><article><span>Rate</span><strong>${sync.blocksPerSecond ?? "—"} blk/s</strong></article><article><span>ETA</span><strong>${formatDuration(sync.etaSeconds)}</strong></article></div><dl class="dialog-metadata"><div><dt>Height</dt><dd>${sync.snapshot.height ?? "—"}</dd></div><div><dt>Headers</dt><dd>${sync.snapshot.headers ?? "—"}</dd></div><div><dt>Peers</dt><dd>${sync.snapshot.peers ?? "—"}</dd></div><div><dt>Peer quality</dt><dd>${sync.peerQuality.state}</dd></div><div><dt>Stalled</dt><dd>${sync.stall.stalled ? "Yes" : "No"}</dd></div></dl><h3>Recommendations</h3><ul class="recommendations">${recommendations}</ul></section>
    <section id="syncPerformanceView" hidden><div class="performance-toolbar"><p>Read-only measurement of sync throughput, peers, CPU, memory, and block I/O.</p><button id="runSyncPerformance" class="primary">Measure performance</button></div><div id="syncPerformanceResults" class="performance-results"><div class="ops-empty-state">Run a performance measurement. Repeating it builds short-window averages in memory.</div></div></section>`;
  const statusView=document.getElementById("syncStatusView"), performanceView=document.getElementById("syncPerformanceView");
  document.querySelectorAll("[data-sync-view]").forEach((button)=>button.addEventListener("click",()=>{const mode=button.dataset.syncView;document.querySelectorAll("[data-sync-view]").forEach((item)=>item.classList.toggle("active",item===button));statusView.hidden=mode!=="status";performanceView.hidden=mode!=="performance";}));
  const fr=(v,suffix)=>Number.isFinite(Number(v))?`${Number(v).toFixed(2)} ${suffix}`:"Collecting…"; const fp=(v)=>Number.isFinite(Number(v))?`${Number(v).toFixed(1)}%`:"—";
  const render=(p)=>{const latest=p.throughput?.latest||{}, five=p.throughput?.fiveMinute||{}, peers=p.peers||{}, resources=p.resources||{}, memory=resources.memory||{}, io=resources.blockIo||{}, recs=p.analysis?.recommendations||[]; return `<div class="performance-summary"><article><span>Likely bottleneck</span><strong>${p.analysis?.likelyBottleneck||"undetermined"}</strong></article><article><span>Blocks / minute</span><strong>${fr(five.blocksPerMinute ?? latest.blocksPerMinute,"blk/min")}</strong></article><article><span>Progress / hour</span><strong>${fr(((five.progressPerHour ?? latest.progressPerHour) ?? null) === null ? null : (five.progressPerHour ?? latest.progressPerHour)*100,"%/hr")}</strong></article><article><span>Estimated completion</span><strong>${formatDuration(p.throughput?.etaSeconds)}</strong></article></div><div class="performance-columns"><section class="performance-panel"><p class="eyebrow">Peer analysis</p><dl class="dialog-metadata"><div><dt>Connected peers</dt><dd>${peers.count ?? "—"}</dd></div><div><dt>Outbound</dt><dd>${peers.outboundCount ?? "—"}</dd></div><div><dt>Average ping</dt><dd>${peers.averagePingMs ?? "—"} ms</dd></div><div><dt>Best ping</dt><dd>${peers.bestPingMs ?? "—"} ms</dd></div></dl><div class="performance-peer-list">${(peers.peers||[]).slice(0,8).map((peer)=>`<article><strong>${peer.address||"unknown peer"}</strong><span>${peer.pingMs ?? "—"} ms · blocks ${peer.syncedBlocks ?? "—"}</span></article>`).join("") || '<div class="ops-empty-state">No peer detail available.</div>'}</div></section><section class="performance-panel"><p class="eyebrow">Runtime resources</p><dl class="dialog-metadata"><div><dt>Container CPU</dt><dd>${fp(resources.cpuPercent)}</dd></div><div><dt>Memory</dt><dd>${fp(memory.usedPercent)}</dd></div><div><dt>Block reads</dt><dd>${formatBytes(io.readBytes)}</dd></div><div><dt>Block writes</dt><dd>${formatBytes(io.writeBytes)}</dd></div></dl><p class="performance-note">CPU can exceed 100% when the node uses more than one core.</p></section></div><section class="performance-panel"><p class="eyebrow">Recommendations</p><ul class="recommendations">${recs.map((item)=>`<li class="recommendation ${item.severity}"><strong>${item.code}</strong><span>${item.message}</span></li>`).join("")}</ul></section><p class="performance-observation-count">${p.throughput?.observationCount ?? 0} in-memory observation(s)</p>`;};
  document.getElementById("runSyncPerformance")?.addEventListener("click",async()=>{const target=document.getElementById("syncPerformanceResults");target.innerHTML='<div class="ops-inline-loading">Measuring BCH performance…</div>';const result=await fetchJsonWithTimeout("/api/sync/performance",{cache:"no-store"},30000);target.innerHTML=result.ok?render(result.payload):`<div class="ops-result-card warning"><strong>Performance measurement unavailable</strong><p>${result.payload?.message||result.payload?.error||`HTTP ${result.status}`}</p></div>`;});
  dialog.showModal();
}
'''
s=s[:start]+replacement+s[end:]; js.write_text(s)
c=css.read_text()
if '/* SBP-047 — sync performance diagnostics */' not in c:
    c += '''\n/* SBP-047 — sync performance diagnostics */\n.sync-manager-tabs{display:flex;gap:7px;margin:12px 0 16px;padding-bottom:10px;border-bottom:1px solid rgba(83,145,224,.16)}.sync-tab{padding:8px 13px;border:1px solid rgba(83,145,224,.22);border-radius:9px;background:rgba(7,22,38,.78);color:var(--muted);cursor:pointer}.sync-tab.active{border-color:rgba(77,156,255,.55);background:rgba(26,103,182,.28);color:var(--text)}.performance-toolbar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:12px}.performance-toolbar p,.performance-note,.performance-observation-count{color:var(--muted);font-size:11px}.performance-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:10px}.performance-summary article,.performance-panel{padding:12px;border:1px solid rgba(83,145,224,.18);border-radius:11px;background:rgba(5,17,31,.58)}.performance-summary span{display:block;margin-bottom:5px;color:var(--muted);font-size:10px}.performance-summary strong{font-size:14px}.performance-columns{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-bottom:9px}.performance-peer-list{display:grid;gap:5px;margin-top:8px}.performance-peer-list article{display:flex;justify-content:space-between;gap:10px;padding:7px 8px;border:1px solid rgba(83,145,224,.12);border-radius:8px;background:rgba(4,14,26,.55)}.performance-peer-list strong{overflow:hidden;text-overflow:ellipsis;font-size:10px}.performance-peer-list span{color:var(--muted);font-size:9px;white-space:nowrap}.performance-observation-count{margin-top:9px;text-align:right}@media(max-width:700px){.performance-summary,.performance-columns{grid-template-columns:1fr}.performance-toolbar{align-items:stretch;flex-direction:column}}\n'''
css.write_text(c)
